using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace SO.Domain.UseCases.Admin.Models
{
    public class CityModel
    {
        /// <summary>
        /// If request for City creation - should be 0
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Will be generated by program if null, empty or "string"
        /// </summary>
        public string Name { get; set; }

        [Required]
        public DateTime FoundationDate { get; set; }

        public CityScreenLayoutModel ScreenLayout { get; set; }
    }

    public class CityScreenLayoutModel
    {
        public int PercentageX { get; set; }

        public int PercentageY { get; set; }
    }
}
